### ISSUE TITLE
Be on the Powered By Faust page ?

### ISSUE THREAD

**Issue by sletz** [zeloe/ReverbZen#1]
Nice project ! Are you interested to be added on the [Powered By Faust page](https://faust.grame.fr/community/made-with-faust/)?

If yes do you have some more explanations of the Reverb ? And a nice screenshot? Thanks.

**Comment by zeloe** [comment]
thank you! Yes, I am in interested. 
I added more explanations in readme and a screenshoot.

**Comment by sletz** [comment]
Done here https://faust.grame.fr/community/made-with-faust/#reverbzen, but the introductory paragraph is quite tiny. If you develop it a bit in your README, then I can copy it. Thanks !

**Comment by zeloe** [comment]
Thank you very much. I added some lines to give an overview on how it works.

**Comment by sletz** [comment]
Done: https://faust.grame.fr/community/made-with-faust/#reverbzen thanks!
